In [2]:
import numpy as np
print(np.__version__)

2.2.3


In [3]:
x = np.array([1,2,3])

In [4]:
x.shape

(3,)

In [8]:
arr =np.arange(9)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
o= arr.reshape(3,3)

In [28]:
arr.shape

(9,)

In [29]:
o.shape

(3, 3)

In [36]:
print(o)
o.sum(axis=0)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 9, 12, 15])

In [37]:
print(o)
o.sum(axis=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 3, 12, 21])

In [40]:
print(o)
o.T

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [39]:
o.sum(axis=0)

array([ 9, 12, 15])

In [41]:
o.ndim

2

In [61]:
oo=o.T

In [63]:
oo

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [62]:
for item in oo.flat:
    print(item)

0
3
6
1
4
7
2
5
8


In [65]:
oo.nbytes

72

In [67]:
oneD=np.array([1,23,4,53])

In [68]:
oneD.argmax()

np.int64(3)

In [69]:
oneD.argmin()

np.int64(0)

In [70]:
oneD.argsort()

array([0, 2, 1, 3])

In [71]:
o

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
oo

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [73]:
oo.argmin()

np.int64(0)

In [74]:
oo.argmax()

np.int64(8)

In [75]:
oo.argmax(axis=0)

array([2, 2, 2])

In [76]:
oo.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [77]:
oo.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [95]:
mat = np.array([[9, 3, 6],
       [1, 0, 7],
       [2, 0, 1]])

In [80]:
print(oo)
print(mat)
oo + mat

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[9 3 6]
 [1 0 7]
 [2 5 1]]


array([[ 9,  6, 12],
       [ 2,  4, 14],
       [ 4, 10,  9]])

In [81]:
oo * mat

array([[ 0,  9, 36],
       [ 1,  0, 49],
       [ 4, 25,  8]])

In [83]:
print(mat)
np.sqrt(mat)

[[9 3 6]
 [1 0 7]
 [2 5 1]]


array([[3.        , 1.73205081, 2.44948974],
       [1.        , 0.        , 2.64575131],
       [1.41421356, 2.23606798, 1.        ]])

In [84]:
mat.min()

np.int64(0)

In [85]:
mat.sum()

np.int64(34)

In [93]:
print(oo)
np.where(oo>6)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


(array([1, 2]), array([2, 2]))

In [97]:
print(oo)
np.where(oo>3)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


(array([0, 1, 1, 2, 2]), array([2, 1, 2, 1, 2]))

In [96]:
np.count_nonzero(mat)

7

In [3]:
yash = np.array([[19,43,12],[32,13,11],[18,20,43]])

In [6]:
np.shape(yash)

(3, 3)

In [7]:
yash

array([[19, 43, 12],
       [32, 13, 11],
       [18, 20, 43]])

In [8]:
yash.ravel()

array([19, 43, 12, 32, 13, 11, 18, 20, 43])

In [9]:
yash.reshape(3,3)

array([[19, 43, 12],
       [32, 13, 11],
       [18, 20, 43]])

In [11]:
yash = yash.T

In [12]:
yash

array([[19, 32, 18],
       [43, 13, 20],
       [12, 11, 43]])

In [13]:
adi = np.array([[9, 2, 8],
       [3, 3, 0],
       [2, 1, 3]])

In [14]:
yash + adi

array([[28, 34, 26],
       [46, 16, 20],
       [14, 12, 46]])

In [15]:
np.argsort(yash)

array([[2, 0, 1],
       [1, 2, 0],
       [1, 0, 2]])

In [19]:
print(yash)
yash.argsort(axis=1)

[[19 32 18]
 [43 13 20]
 [12 11 43]]


array([[2, 0, 1],
       [1, 2, 0],
       [1, 0, 2]])